### ISSUE TITLE
Add id: signature choice to signature loop

### ISSUE THREAD

**Issue by miabonardi** [Reidel-Law-Firm/docassemble-LLC#5]
Which lines of code need to be added for id: signature choice to appear as a screen in the signature loop?

**Comment by miabonardi** [comment]
@nonprofittechy could you add the logic that asks for the signatures in a specific order

**Comment by nonprofittechy** [comment]
@miabonardi, what order does it need to be in?

**Comment by nonprofittechy** [comment]
We want to ask if someone is ready to sign immediately before they get the chance to actually sign.
